import {
  CustomerOrder,
  DonutData,
  Indicator,
  IndicatorData,
  Objective,
  ObjectiveData,
  UserSettings,
} from "@/types";

export const customerOrders: CustomerOrder[] = [
  {
    id: 1,
    name: "Press",
    address: "London",
    date: "22.08.2022",
    status: "Delivered",
    price: "$920",
    avatar: "P",
  },
  {
    id: 2,
    name: "Marina",
    address: "Man city",
    date: "24.08.2022",
    status: "Processed",
    price: "$452",
    avatar: "M",
  },
  {
    id: 3,
    name: "Alex",
    address: "Unknown",
    date: "18.08.2022",
    status: "Cancelled",
    price: "$1200",
    avatar: "A",
  },
  {
    id: 4,
    name: "Robert",
    address: "New York",
    date: "03.08.2022",
    status: "Delivered",
    price: "$1235",
    avatar: "R",
  },
];

export const userTypeData: DonutData[] = [
  { label: "On Track", value: 65, color: "#ffbc11" },
  { label: "At Risk", value: 25, color: "#FFE580" },
  { label: "Delayed", value: 10, color: "#FFFBEF" },
];

export const subscriptionData: DonutData[] = [
  { label: "Complete", value: 70, color: "#3b82f6" },
  { label: "Pending", value: 30, color: "#93c5fd" },
];

export const sampleObjectives: Objective[] = [
  {
    id: 1,
    name: "An industrialised and diversified economy",
    description:
      "Increase industrial satisfaction scores by 20% through improved service delivery",
    numIndicators: 5,
    status: "Active",
    priority: "High",
    assignedTo: "Sarah Johnson",
    createdAt: "2024-01-15",
    dueDate: "2024-06-30",
    progress: 75,
    category: "Human Resources",
  },
  {
    id: 2,
    name: "Enhanced citizenry participation in the economy",
    description:
      "Decrease average customer support response time to under 2 hours",
    numIndicators: 3,
    status: "Active",
    priority: "High",
    assignedTo: "Mike Chen",
    createdAt: "2024-02-01",
    dueDate: "2024-04-15",
    progress: 45,
    category: "Policy and Planning",
  },
  {
    id: 3,
    name: "Competitive private sector",
    description:
      "Complete comprehensive training for all customer service representatives",
    numIndicators: 8,
    status: "Completed",
    priority: "Medium",
    assignedTo: "Lisa Rodriguez",
    createdAt: "2023-12-10",
    dueDate: "2024-03-01",
    progress: 100,
    category: "Research",
  },
];

export const sampleIndicators: Indicator[] = [
  {
    id: 1,
    name: "Share of Manufacturing value-added in GDP",
    description: "Percentage of GDP contributed by the manufacturing sector",
    baseline: 3.2,
    target: 4.5,
    actual: 4.1,
    unit: "Score (1-5)",
    assignee: "Sarah Johnson",
    category: "Human Resources",
    objective: "Increase Customer Satisfaction",
    createdAt: "2024-01-15",
    updatedAt: "2024-03-10",
    status: "On Track",
    frequency: "Monthly",
  },
  {
    id: 2,
    name: "Share of Service value-added in GDP",
    description: "Percentage of GDP contributed by the service sector",
    baseline: 4.5,
    target: 2.0,
    actual: 2.3,
    unit: "Percentage",
    assignee: "Mike Chen",
    category: "Policy and Planning",
    objective: "Reduce Response Time",
    createdAt: "2024-02-01",
    updatedAt: "2024-03-12",
    status: "On Track",
    frequency: "Daily",
  },
  {
    id: 3,
    name: "Growth rate in export share of manufactures and services",
    description:
      "Percentage increase in export share of manufactures and services",
    baseline: 65,
    target: 95,
    actual: 88,
    unit: "Percentage",
    assignee: "Lisa Rodriguez",
    category: "Information Technology",
    objective: "Employee Training Program",
    createdAt: "2023-12-10",
    updatedAt: "2024-03-08",
    status: "On Track",
    frequency: "Monthly",
  },
  {
    id: 4,
    name: "GDP Growth Rate",
    description:
      "Annual percentage growth rate of GDP at market prices based on constant local currency",
    baseline: 97.5,
    target: 99.9,
    actual: 98.2,
    unit: "Percentage",
    assignee: "David Kim",
    category: "Research",
    objective: "Policy and Planning",
    createdAt: "2024-02-20",
    updatedAt: "2024-03-13",
    status: "At Risk",
    frequency: "Daily",
  },
  {
    id: 5,
    name: "Non-extractive export earnings",
    description:
      "Percentage increase in non-extractive export earnings compared to previous period",
    baseline: 12.5,
    target: 18.0,
    actual: 11.8,
    unit: "USD",
    assignee: "Emma Wilson",
    category: "Finance",
    objective: "Market Research Analysis",
    createdAt: "2024-01-30",
    updatedAt: "2024-03-05",
    status: "Off Track",
    frequency: "Quarterly",
  },
  {
    id: 6,
    name: "Youth employment rate",
    description: "Percentage of youth (ages 15-24) who are employed",
    baseline: 40,
    target: 50,
    actual: 45,
    unit: "Percentage",
    assignee: "James Smith",
    category: "Procurement",
    objective: "Revenue Growth Initiative",
    createdAt: "2024-01-05",
    updatedAt: "2024-03-11",
    status: "On Track",
    frequency: "Monthly",
  },
  {
    id: 7,
    name: "Services productivity growth rate",
    description: "Percentage increase in productivity of the services sector",
    baseline: 3.8,
    target: 4.3,
    actual: 4.5,
    unit: "Percentage",
    assignee: "Lisa Rodriguez",
    category: "Human Resources",
    objective: "Employee Training Program",
    createdAt: "2024-01-20",
    updatedAt: "2024-03-09",
    status: "Achieved",
    frequency: "Quarterly",
  },
  {
    id: 8,
    name: "Manufacturing productivity growth rate",
    description:
      "Percentage increase in productivity of the manufacturing sector",
    baseline: 2.8,
    target: 4.5,
    actual: 3.2,
    unit: "Percentage",
    assignee: "James Smith",
    category: "Procurement",
    objective: "Revenue Growth Initiative",
    createdAt: "2024-02-10",
    updatedAt: "2024-03-12",
    status: "At Risk",
    frequency: "Weekly",
  },
];

export const sampleObjectivesR: ObjectiveData[] = [
  {
    id: 1,
    name: "An industrialised and diversified economy",
    category: "Human Resources",
    status: "Active",
    progress: 75,
    indicators: [],
  },
  {
    id: 2,
    name: "Enhanced citizenry participation in the economy",
    category: "Policy and Planning",
    status: "Active",
    progress: 85,
    indicators: [],
  },
  {
    id: 3,
    name: "Competitive private sector",
    category: "Human Resources",
    status: "Completed",
    progress: 100,
    indicators: [],
  },
  {
    id: 4,
    name: "Revenue Growth Initiative",
    category: "Sales",
    status: "Active",
    progress: 60,
    indicators: [],
  },
];

export const sampleIndicatorsR: IndicatorData[] = [
  {
    id: 1,
    name: "Share of manufacturing value-added in GDP",
    baseline: 3.2,
    target: 4.5,
    actual: 4.1,
    unit: "Score (1-5)",
    status: "On Track",
    objective: "Increase Customer Satisfaction",
    assignee: "Sarah Johnson",
    category: "Human Resources",
    trend: "up",
    history: [
      { date: "2024-01-01", value: 3.2 },
      { date: "2024-02-01", value: 3.5 },
      { date: "2024-03-01", value: 3.8 },
      { date: "2024-04-01", value: 4.1 },
    ],
  },
  {
    id: 2,
    name: "Share of Service value-added in GDP",
    baseline: 4.5,
    target: 2.0,
    actual: 2.3,
    unit: "Hours",
    status: "On Track",
    objective: "Reduce Response Time",
    assignee: "Mike Chen",
    category: "Policy and Planning",
    trend: "down",
    history: [
      { date: "2024-01-01", value: 4.5 },
      { date: "2024-02-01", value: 3.8 },
      { date: "2024-03-01", value: 2.9 },
      { date: "2024-04-01", value: 2.3 },
    ],
  },
  {
    id: 3,
    name: "Growth rate in export share of manufactures and services",
    baseline: 65,
    target: 95,
    actual: 88,
    unit: "Percentage",
    status: "On Track",
    objective: "Employee Training Program",
    assignee: "Lisa Rodriguez",
    category: "Human Resources",
    trend: "up",
    history: [
      { date: "2024-01-01", value: 65 },
      { date: "2024-02-01", value: 72 },
      { date: "2024-03-01", value: 80 },
      { date: "2024-04-01", value: 88 },
    ],
  },
  {
    id: 4,
    name: "Rank of top 5 commodity exports",
    baseline: 1250,
    target: 1600,
    actual: 1520,
    unit: "USD",
    status: "On Track",
    objective: "Revenue Growth Initiative",
    assignee: "James Smith",
    category: "Procurement",
    trend: "up",
    history: [
      { date: "2024-01-01", value: 1250 },
      { date: "2024-02-01", value: 1320 },
      { date: "2024-03-01", value: 1420 },
      { date: "2024-04-01", value: 1520 },
    ],
  },
  {
    id: 5,
    name: "Non-extractive export earnings",
    baseline: 3.8,
    target: 4.3,
    actual: 4.5,
    unit: "Score (1-5)",
    status: "Achieved",
    objective: "Employee Training Program",
    assignee: "Lisa Rodriguez",
    category: "Human Resources",
    trend: "up",
    history: [
      { date: "2024-01-01", value: 3.8 },
      { date: "2024-02-01", value: 4.0 },
      { date: "2024-03-01", value: 4.2 },
      { date: "2024-04-01", value: 4.5 },
    ],
  },
];

export const sampleUser: UserSettings = {
  profile: {
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@company.com",
    phone: "+1 (555) 123-4567",
    jobTitle: "Senior Manager",
    department: "Operations",
    timezone: "America/New_York",
    language: "en",
    avatar: "",
  },
  notifications: {
    email: true,
    push: true,
    sms: false,
    weeklyReports: true,
    objectiveUpdates: true,
    indicatorAlerts: true,
    systemUpdates: false,
    marketingEmails: false,
  },
  preferences: {
    theme: "dark",
    soundEnabled: true,
    defaultDashboard: "main",
    itemsPerPage: 25,
    autoRefresh: true,
    refreshInterval: 300,
    compactMode: false,
  },
  privacy: {
    profileVisibility: "team",
    showOnlineStatus: true,
    allowDataExport: true,
    shareAnalytics: false,
  },
  security: {
    twoFactorEnabled: false,
    sessionTimeout: 480,
    passwordExpiry: 90,
    loginNotifications: true,
  },
};

export const timezones = [
  { value: "America/New_York", label: "Eastern Time (ET)" },
  { value: "America/Chicago", label: "Central Time (CT)" },
  { value: "America/Denver", label: "Mountain Time (MT)" },
  { value: "America/Los_Angeles", label: "Pacific Time (PT)" },
  { value: "Europe/London", label: "Greenwich Mean Time (GMT)" },
  { value: "Europe/Paris", label: "Central European Time (CET)" },
  { value: "Asia/Tokyo", label: "Japan Standard Time (JST)" },
];

export const languages = [
  { value: "en", label: "English" },
  { value: "es", label: "Spanish" },
  { value: "fr", label: "French" },
  { value: "de", label: "German" },
  { value: "it", label: "Italian" },
  { value: "pt", label: "Portuguese" },
  { value: "ja", label: "Japanese" },
];

export const departments = [
  { value: "Operations", label: "Operations" },
  { value: "Sales", label: "Sales" },
  { value: "Marketing", label: "Marketing" },
  { value: "Human Resources", label: "Human Resources" },
  { value: "Technology", label: "Technology" },
  { value: "Finance", label: "Finance" },
  { value: "Customer Service", label: "Customer Service" },
];
