/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppReportsRouteRouteImport } from './routes/_app/reports/route'
import { Route as AppObjectiveRouteRouteImport } from './routes/_app/objective/route'
import { Route as AppIndicatorsRouteRouteImport } from './routes/_app/indicators/route'
import { Route as AppDashboardRouteRouteImport } from './routes/_app/dashboard/route'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsRouteRoute = AppReportsRouteRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppObjectiveRouteRoute = AppObjectiveRouteRouteImport.update({
  id: '/objective',
  path: '/objective',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIndicatorsRouteRoute = AppIndicatorsRouteRouteImport.update({
  id: '/indicators',
  path: '/indicators',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRouteRoute = AppDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRouteRoute
  '/indicators': typeof AppIndicatorsRouteRoute
  '/objective': typeof AppObjectiveRouteRoute
  '/reports': typeof AppReportsRouteRoute
  '/settings': typeof AppSettingsRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRouteRoute
  '/indicators': typeof AppIndicatorsRouteRoute
  '/objective': typeof AppObjectiveRouteRoute
  '/reports': typeof AppReportsRouteRoute
  '/settings': typeof AppSettingsRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRoute
  '/_app/dashboard': typeof AppDashboardRouteRoute
  '/_app/indicators': typeof AppIndicatorsRouteRoute
  '/_app/objective': typeof AppObjectiveRouteRoute
  '/_app/reports': typeof AppReportsRouteRoute
  '/_app/settings': typeof AppSettingsRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/indicators'
    | '/objective'
    | '/reports'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/indicators'
    | '/objective'
    | '/reports'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/dashboard'
    | '/_app/indicators'
    | '/_app/objective'
    | '/_app/reports'
    | '/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/objective': {
      id: '/_app/objective'
      path: '/objective'
      fullPath: '/objective'
      preLoaderRoute: typeof AppObjectiveRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/indicators': {
      id: '/_app/indicators'
      path: '/indicators'
      fullPath: '/indicators'
      preLoaderRoute: typeof AppIndicatorsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardRouteRoute: typeof AppDashboardRouteRoute
  AppIndicatorsRouteRoute: typeof AppIndicatorsRouteRoute
  AppObjectiveRouteRoute: typeof AppObjectiveRouteRoute
  AppReportsRouteRoute: typeof AppReportsRouteRoute
  AppSettingsRouteRoute: typeof AppSettingsRouteRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRouteRoute: AppDashboardRouteRoute,
  AppIndicatorsRouteRoute: AppIndicatorsRouteRoute,
  AppObjectiveRouteRoute: AppObjectiveRouteRoute,
  AppReportsRouteRoute: AppReportsRouteRoute,
  AppSettingsRouteRoute: AppSettingsRouteRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
